---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang
  commands:
  - go build ./cmd/skogul

- name: test
  image: golang
  commands:
  - go test -short ./...
  - if [ "x$(gofmt -s -d .)" != "x" ]; then gofmt -s -d .; exit 1; fi
  - go vet ./...
  depends_on:
    - build

- name: prepare-release
  image: golang
  commands:
  - apt-get update
  - apt-get -y install python-docutils bzip2 gawk
  - ./make-release.sh ${DRONE_TAG}
  depends_on:
    - test
  when:
    event:
    - tag

- name: prepare-centos-release
  image: centos:7
  environment:
    SHELL: /bin/bash
  commands:
  - yum install -y git python-docutils rpm-build wget
  - wget https://storage.googleapis.com/golang/getgo/installer_linux
  - chmod +x installer_linux
  - ./installer_linux
  - source /root/.bash_profile
  - ./make-rpm.sh ${DRONE_TAG}
  depends_on:
    - test
  when:
    event:
    - tag

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release_api_key
    checksum:
    - sha256
    draft: true
    files:
    - skogul-*.tar.bz2
    - skogul-*.rpm
    note: notes
    title: Skogul ${DRONE_TAG}
  depends_on:
    - prepare-release
    - prepare-centos-release
  when:
    event:
    - tag

...
