---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang
  commands:
  - go build ./cmd/skogul

- name: test
  image: golang
  commands:
  - go test -short ./...
  - if [ "x$(gofmt -s -d .)" != "x" ]; then gofmt -s -d .; exit 1; fi
  - go vet ./...

- name: prepare-release
  image: golang
  commands:
  - apt update
  - apt -y install python-docutils bzip2
  - ./make-release.sh ${DRONE_TAG}
  when:
    event:
    - tag

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release_api_key
    checksum:
    - sha256
    draft: true
    files:
    - skogul-*.tar.bz2
    note: |
      ${DRONE_COMMIT_MESSAGE}
    title: Skogul ${DRONE_TAG}
  when:
    event:
    - tag

...
