---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - go build ./cmd/skogul

- name: test
  image: golang
  commands:
  - go test -short ./...
  - if [ "x$(gofmt -s -d .)" != "x" ]; then gofmt -s -d .; exit 1; fi
  - go vet ./...

- name: prepare-release
  image: golang
  commands:
  - apt update
  - apt -y install python-docutils
  - ./make-release.sh
  when:
    event: tag

- name: publish
  image: plugins/github-release
  settings:
    title: Skogul ${DRONE_TAG}
    note: ${DRONE_COMMIT_MESSAGE}
    draft: true
    api_key:
      from_secret: github_release_api_key
    files:
      - skogul-*.tar.bz2
    checksum:
      - sha256
  when:
    event: tag
